title: Sagar D. Patil
logo: assets/images/dp.png

description: "Identity & Access Management Professional (Information Security)"
show_downloads: false

# Navigation links (Optional)
nav:
  - text: "Home"
    url: "/"
  - text: "Contact"
    url: "/contact"
  - text: "Blog"
    url: "/blog"
  - text: "Portfolio"
    url: "/portfolio"

# Theme Configuration
theme: jekyll-theme-minimal
