title: Sagar D. Patil
logo: assets/images/dp.png

description: "Identity & Access Management Professional (Information Security)"
show_downloads: true

# Download My Portfolio
portfolio_pdf: "assets/downloads/portfolio.pdf"

theme: jekyll-theme-minimal
